import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const typewriterMono = localFont({
  src: [
    {
      path: '../public/fonts/ComputerModernTypewriter-Regular.woff2',
      weight: '400'
    },
    {
      path: '../public/fonts/ComputerModernTypewriter-Bold.woff2',
      weight: '800',
    },
  ],
  variable: '--font-typewriter-mono'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${typewriterMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
